import Head from "next/head";
import { useState } from "react";
import { Container } from "../styles/index";

export default function Home() {
  const [list, setList] = useState<string>("");
  const [result, setResult] = useState<null | string>(null);

  function containsNumbers(str: string) {
    console.log(str);
    return /\d/.test(str.trim());
  }

  const handleSubmit = () => {
    if (list.length < 0) {
      alert("Insira uma lista");
    }
    var tempList = "";
    const listArray = list.split("-");
    for (let i = 1; i < listArray.length; i++) {
      tempList += `${i} - ${listArray[i].trim().replace(/[0-9]/g, "")} \n`;
    }
    console.log(tempList);
    setResult(tempList);
  };

  return (
    <>
      <Head>
        <title>Party list organizer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <input
          value={list}
          onChange={(e) => {
            setList(e.currentTarget.value);
          }}
          type="text"
        />
        <button onClick={handleSubmit}>Enviar</button>
        {result != null && (
          <button onClick={() => navigator.clipboard.writeText(result)}>
            Copiar resultado
          </button>
        )}
      </Container>
    </>
  );
}
